### ISSUE TITLE
Error 500 on e-link/documents endpoint with template id 3

### ISSUE THREAD

**Issue by davidwabnitz** [freme-project/technical-discussion#117] opened 2016-03-21 14:40 UTC
#### Bug report
* environment: production at api.freme-project.eu, using Google Chrome Canary (latest) on Mac OS X 
* swagger-ui http://api.freme-project.eu/doc/current/api-doc/full.html

##### IS
* error 500
* response body
{
  "exception": "eu.freme.broker.exception.InternalServerErrorException",
  "path": "//e-link/documents/",
  "message": "Unknown problem. Please contact us.",
  "error": "Internal Server Error",
  "status": 500,
  "timestamp": 1458570955530
}

##### SHOULD
* not happen

#### Steps to reproduce
1. as user visit http://api.freme-project.eu/doc/current/api-doc/full.html#!/e-Link/enrich
2. enter body using NIF example provided
3. set templateid to 3
4. hit button 'try it out!'

**Comment by jnehring** [comment] 2016-03-22 09:54
I can reproduce the error.

The template uses SPARQL endpoint http://factforge.net/sparql which is currently unavailable. I guess that this is the source of the error.

We should wait until http://factforge.net/sparql works again and see if that solves the error. When this solves the error we should give a better error message, e.g. 502 - Bad Gateway and "Endpoint http://factforge.net/sparql does not respond".

**Comment by davidwabnitz** [comment] 2016-03-24 09:44
@jnehring could it be that the public sparql endpoint for factforge has been switched off in favor of using it as part of the S4 suite of tools (where I get a rate limited access to https://lod.s4.ontotext.com/v1/FactForge/sparql)?

**Comment by jnehring** [comment] 2016-03-24 10:37
The SPARQL endpoint http://factforge.net/sparql and the whole homepage http://factforge.net is still unavailable. The website http://ontotext.com/factforge-links/ still states that it should be online.

> could it be that the public sparql endpoint for factforge has been switched off in favor of using it as part of the S4 suite of tools

I dont know. Why do you think so?

Unfortunately we can only wait if the factforge endpoint to work again.

@davidwabnitz maybe I can help you to find an alternative to factforge? Do you have a concrete application that requires factforge?

**Comment by jnehring** [comment] 2016-03-29 14:25
Factforge is up and running again and template 3 works also. @davidwabnitz can you please confirm that the issue is solved and then close the issue? Thanks.

**Closed** 2016-04-05 09:24 UTC

**Comment by davidwabnitz** [comment] 2016-04-06 19:05
@jnehring can confirm that it works
